### Service Document
GET http://localhost:4004/browse

### Service $metadata document
GET http://localhost:4004/browse/$metadata

### Browsing Cars
GET http://localhost:4004/browse/Cars?
# &$select=descr,model
# &$expand=currency
# &sap-language=de

### Browsing Manufacturers
GET http://localhost:4004/browse/Manufacturers?
# &$select=name,dateOfBirth,placeOfBirth
# &$expand=books($select=title;$expand=currency)
# &$filter=ID eq 101
# &sap-language=de

### Try to insert into Cars 
POST http://localhost:4004/admin/Cars 
Content-Type: application/json 
{
    "model": "911GT", 
    "stock": 10 
}