### List Cars with their current stocks
GET http://localhost:4004/admin/Cars?$select=ID,stock

### List all Orders
GET http://localhost:4004/admin/Orders?
# &$expand=Items

### Submit Orders
POST http://localhost:4004/browse/Orders
Content-Type: application/json

{ "OrderNo":"testNr", 
"Items":[
    { "car_ID": 100, "amount": 1 },
    { "car_ID": 101, "amount": 1 }
]}

# Sending this three times should result in a 409: 5 exceeds stock for book #201
#{ "car_ID": 101, "amount": 2 }

### ------------------------------------------------------------------------
# Submit Order as authenticated user
# (send that three times to get out-of-stock message)
POST http://localhost:4004/browse/submitOrder
Content-Type: application/json

{ "book":201, "amount":5 }